import AVFoundation
import Foundation
import TechPomodoroCore

/// Plays the completion ding from the tones bundled with the app, optionally several times in a row.
///
/// Foreground only: while the app is suspended the boundary's local notification carries the sound.
/// The audio session is `.ambient`, so the ding respects the silent switch and mixes with whatever
/// else is playing rather than interrupting it.
@MainActor
final class BundledSoundPlayer: SoundPlaying {
    private var pending: [DispatchWorkItem] = []
    /// Held so a sound is not deallocated mid-play.
    private var current: AVAudioPlayer?

    init() {
        try? AVAudioSession.sharedInstance().setCategory(.ambient, options: [.mixWithOthers])
    }

    nonisolated func play(named name: String, times: Int) {
        MainActor.assumeIsolated {
            // A new alert supersedes repeats still queued from the previous one.
            pending.forEach { $0.cancel() }
            pending.removeAll()

            guard let url = BundledSoundCatalog.url(for: name) else { return }
            let player = try? AVAudioPlayer(contentsOf: url)
            current = player
            player?.play()

            // Space the repeats by the tone's own length, so a long bell does not overlap itself.
            let gap = max(0.45, (player?.duration ?? 0.5) + 0.1)
            for repetition in 1..<max(1, times) {
                let item = DispatchWorkItem { [weak self] in
                    MainActor.assumeIsolated {
                        let again = try? AVAudioPlayer(contentsOf: url)
                        self?.current = again
                        again?.play()
                    }
                }
                pending.append(item)
                DispatchQueue.main.asyncAfter(deadline: .now() + gap * Double(repetition), execute: item)
            }
        }
    }
}

/// The tones in the app bundle, generated by `Scripts/make-sounds.swift`. iOS has no system sound
/// folder to read, so this is the whole catalog.
struct BundledSoundCatalog: SoundCatalogProviding {
    /// Shares its name with the macOS default, so the `soundName` default resolves on both platforms.
    static let fallbackName = "Glass"
    static let fileExtension = "caf"

    let availableSoundNames: [String]

    init(bundle: Bundle = .main) {
        let names = (bundle.urls(forResourcesWithExtension: Self.fileExtension, subdirectory: nil) ?? [])
            .map { $0.deletingPathExtension().lastPathComponent }
        availableSoundNames = names.isEmpty ? [Self.fallbackName] : names.sorted()
    }

    /// The stored name if a tone of that name is bundled, otherwise the fallback. A name carried over
    /// from the Mac ("Submarine", say) plays as Glass rather than going silent.
    func resolvedName(for stored: String) -> String {
        availableSoundNames.contains(stored) ? stored : Self.fallbackName
    }

    /// The file for a tone, falling back to the default tone.
    static func url(for name: String, bundle: Bundle = .main) -> URL? {
        bundle.url(forResource: name, withExtension: fileExtension)
            ?? bundle.url(forResource: fallbackName, withExtension: fileExtension)
    }

    /// The file name a notification sound needs: iOS looks it up in the main bundle by name.
    static func notificationFileName(for name: String, bundle: Bundle = .main) -> String {
        let resolved = bundle.url(forResource: name, withExtension: fileExtension) != nil ? name : fallbackName
        return "\(resolved).\(fileExtension)"
    }
}
